config/routes.rb
  get "wms_parameters/make_optional_or_mandatory"

  get "wms_parameters/destroy"

  get "wms_parameters/authorise"

  get "wms_parameters/get_redirect_url"

  get "wms_parameters/destroy_method_param_map"

  get "wms_parameters/find_rest_parameter"

  get "wms_parameters/find_rest_method"

  get "wms_parameters/find_rest_methods"

  get "wms_representations/show"

  get "wms_representations/annotations"

  get "wms_representations/new_popup"

  get "wms_representations/add_new_representations"

  get "wms_representations/destroy"

  get "wms_representations/authorise"

  get "wms_representations/find_rest_method"

  get "wms_representations/find_rest_methods"

  get "wms_representations/find_rest_representation"

  get "wms_representations/get_redirect_url"

  get "wms_representations/destroy_method_rep_map"

  get "wms_resources/new_popup"

  get "wms_resources/add_new_resources"

  get "wms_resources/index"

  get "wms_resources/show"

  get "wms_resources/annotations"

  get "wms_resources/methods"

  get "wms_resources/parse_sort_params"

  get "wms_resources/authorise"

  get "wms_resources/find_wms_service"

  get "wms_resources/find_wms_resource"
=begin

  get "wms_services/new"

  get "wms_services/edit"

=end
 # get "wms_services/test"

  resources :oauth_clients

  match '/oauth/test_request' => 'oauth#test_request', :as => :test_request
  match '/oauth/access_token' => 'oauth#access_token', :as => :access_token
  match '/oauth/request_token' => 'oauth#request_token', :as => :request_token
  match '/oauth/authorize' => 'oauth#authorize', :as => :authorize
  match '/oauth' => 'oauth#index', :as => :oauth
  match '/curation' => 'curation#show', :as => :curation, :via => :get
  match '/curation/reports/potential_duplicate_operations_within_service' => 'curation#potential_duplicate_operations_within_service', :as => :curation_reports_potential_duplicate_operations_within_service, :via => :get
  match '/curation/reports/providers_without_services' => 'curation#providers_without_services', :as => :curation_reports_providers_without_services, :via => :get
  match '/curation/reports/services_missing_annotations' => 'curation#services_missing_annotations', :as => :curation_reports_services_missing_annotations, :via => [:get, :post]
  match '/curation/tools/copy_annotations' => 'curation#copy_annotations', :as => :curation_tools_copy_annotations, :via => [:get, :post]
  match '/curation/tools/copy_annotations_preview' => 'curation#copy_annotations_preview', :as => :curation_tools_copy_annotations_preview, :via => :post
  match '/curation/reports/annotation_level' => 'curation#annotation_level', :as => :curation_annotation_level, :via => :get
  match '/curation/reports/links_checker' => 'curation#links_checker', :as => :link_checker, :via => :get
  match '/curation/tools/download_latest_csv' => 'curation#download_latest_csv', :as => :download_latest_csv, :via => :get
  match '/curation/tools/csv_export' => 'curation#download_csv_page', :as => :download_csv_page, :via => :get
  match '/curation/elixir_curation' => 'curation#elixir_curation', :as => :elixir_curation, :via => :get

  match '/api.:format' => 'api#show', :as => :api
  match '/lookup.:format' => 'lookup#show', :as => :lookup
  match '/lookup' => 'lookup#show', :as => :lookup
=begin

  match '/wms_services/test' => 'wms_services#test'
=end

  resources :announcements

  resources :service_tests do

    member do
      get :results
      put :enable
      put :disable
      post :new_url_monitor_popup
      post :create_monitoring_endpoint
      post :edit_monitoring_endpoint_by_popup
      post :update_monitoring_endpoint
    end

  end

  resources :test_results

  resources :test_scripts do

    member do
      get :download
    end

  end

  match '/fail/:http_code' => 'fail#index', :as => :fail_page
  match '/stats' => 'stats#index', :as => :stats_index
  match '/stats/refresh' => 'stats#refresh', :as => :refresh_stats, :via => :post

  resources :stats do

    collection do
      get :general
      get :metadata
      get :tags
      get :search
    end
  end

  resources :categories do

    member do
      get :services
    end

  end

  resources :registries do

    member do
      get :annotations_by
      get :services
    end

  end

  resources :agents do

    member do
      get :annotations_by
    end

  end

  resources :annotations do

    collection do
      post :create_multiple
      post :new_popup
      post :create_inline
      post :filtered_index
      get :filters
      post :bulk_create
    end

    member do
      post :edit_popup
      post :promote_alternative_name
      get :download
    end

  end

  resources :annotation_attributes do

    member do
      get :annotations
    end

  end

  resources :tags, :only => [:index, :show, :destroy] do

    collection do
      delete :destroy_taggings
      post :auto_complete
    end


  end

  match '/search/auto_complete' => 'search#auto_complete', :as => :search_auto_complete, :via => :post
  match '/search/ignore_last' => 'search#ignore_last', :as => :ignore_last_search, :via => :post
  match '/search.:format' => 'search#show', :as => :search, :via => [:get, :post]
  match '/search' => 'search#show', :as => :search, :via => [:get, :post]
  match '/search/by_data.:format' => 'search#by_data', :as => :search_by_data, :via => [:get, :post]
  match '/search/by_data' => 'search#by_data', :as => :search_by_data, :via => [:post, :get]



  resources :service_providers do

    collection do
      post :filtered_index
      get :filters
      post :edit_by_popup
      post :auto_complete
    end

    member do
      get :annotations_by
      get :annotations
      get :services
      post :edit_by_popup
      put :upload_logo
      delete :remove_logo

      #for loading tab partials
      get :hostnames
      get :profile
      get :services
    end

  end

  resources :service_provider_hostnames do
    collection do
      post :reassign_provider_by_popup
      post :reassign_provider
    end
  end

  resources :service_deployments do

    member do
      get :annotations
      post :edit_location_by_popup
      post :update_location
    end

  end

  resources :users do

    collection do
      get :whoami
      get :activate_account
      post :filtered_index
      get :rpx_merge_setup
      get :filters
      post :rpx_merge
    end

    member do
      put :remove_curator
      get :annotations_by
      put :deactivate
      get :change_password
      post :change_password
      get :favourites
      get :rpx_update
      post :rpx_update
      put :activate
      get :services_responsible
      get :services_annotated
      get :services_submitted
      get :service_status_notifications
      get :service_status
      get :saved_searches
      get :services
      put :make_curator
    end

  end

  match '/termsofuse' => 'termsofuse#index'

  match '/session' => 'sessions#create', :as => :session, :via => :post

  if ENABLE_RPX
    match '/session/rpx_token' => 'sessions#rpx_token', :as => :session_rpx_token
  end

  match '/register' => 'users#new', :as => :register
  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/signin' => 'sessions#new', :as => :signin
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/activate_account/:security_token' => 'users#activate_account', :as => :activate_account, :security_token => nil
  match '/forgot_password' => 'users#forgot_password', :as => :forgot_password
  match '/request_reset_password' => 'users#request_reset_password', :as => :request_reset_password
  match '/reset_password/:security_token' => 'users#reset_password', :as => :reset_password, :security_token => nil
  match '/contact' => 'contact#create', :as => :submit_feedback, :via => :post
  match '/contact' => 'contact#index', :as => :contact, :via => :get
  match '/' => 'home#index', :as => :home
  match '/index.:format' => 'home#index', :as => :activity_feed
  match '/status_changes.:format' => 'home#status_changes', :as => :status_changes_feed

  match '/latest' => 'latest#show', :as => :latest
  match 'service_providers/auto_complete' => 'service_providers#auto_complete', :as => :service_provider_auto_complete, :via => :post


  resources :latest do
    collection do
      get :activity
      get :monitoring
      get :contributors
      get :services
    end
  end

  resources :rest_services do

    member do
      get :methods
      get :annotations
      get :deployments
      get :resources
      post :edit_base_endpoint_by_popup
    end

    collection do
      post :update_base_endpoint
      get :edit_base_endpoint_by_popup
    end

  end
  
 resources :wms_services do

    collection do
      get :methods
      get :test
    end

  end

  resources :rest_resources do

    member do
      get :methods
      get :annotations
    end

    collection do
      post :new_popup
      post :add_new_resources
    end

  end

  resources :rest_methods do

    collection do
      post :filtered_index
      get :filters
    end

    member do
      post :update_group_name
      post :group_name_auto_complete
      get :inputs
      get :outputs
      get :annotations
      post :inline_add_endpoint_name
      post :edit_group_name_popup
      post :update_resource_path
      put :remove_endpoint_name
      post :edit_endpoint_name_popup
      post :edit_resource_path_popup
      post :update_endpoint_name
    end

  end

  resources :rest_parameters do

    member do
      get :annotations
      post :inline_add_default_value
      put :make_optional_or_mandatory
      post :update_constrained_options
      put :remove_default_value
      get :remove_constrained_options
      post :update_default_value
      post :edit_constrained_options_popup
      post :edit_default_value_popup
      get :localise_globalise_parameter
    end

    collection do
      get :add_new_parameters

app/models/announcement.rb
# BioCatalogue: app/models/announcement.rb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

class Announcement < ActiveRecord::Base
  
  if ENABLE_TRASHING
    acts_as_trashable
  end
  
  belongs_to :user

  validates_presence_of :user_id,
                        :title

  before_save :check_authorisation
  
  def self.latest(limit=5)
    self.all(              :order => "created_at DESC",
              :limit => limit)
  end
  
  def check_authorisation
    if !self.user_id.blank? and BioCatalogue::Auth.allow_user_to_curate_thing?(self.user, :announcements)
      return true
    else
      errors.add_to_base("Only admins and curators can create announcements")
      return false
    end
  end
  
end

app/controllers/announcements_controller.rb
# BioCatalogue: app/controllers/announcements_controller.rb
#
# Copyright (c) 2008-2009, University of Manchester, The European Bioinformatics
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details.

class AnnouncementsController < ApplicationController
  
  before_filter :disable_action_for_api, :except => [ :index ]
  
  before_filter :login_or_oauth_required, :except => [ :show, :index ]
  before_filter :authorise, :except => [ :show, :index ]
  
  before_filter :find_announcement, :only => [ :show, :edit, :update, :destroy ]
  
  before_filter :find_announcements, :only => [ :index ]
  
  before_filter :setup_for_feed, :only => [ :index ]
  
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml  # index.xml.builder
      format.atom # index.atom.builder
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  def new
    @announcement = Announcement.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  def create
    params[:announcement][:user_id] = current_user.id
    
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        flash[:notice] = 'Announcement was successfully created'
        format.html { redirect_to(@announcement) }
        format.xml  { render :xml => @announcement, :status => :created, :location => @announcement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        flash[:notice] = 'Announcement was successfully updated'
        format.html { redirect_to(@announcement) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @announcement.destroy
    
    flash[:notice] = "Announcement deleted"
    
    respond_to do |format|
      format.html { redirect_to(announcements_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
  
  def find_announcement
    @announcement = Announcement.find(params[:id])
  end
  
  def find_announcements
    @announcements = Announcement.paginate(:page => params[:page],
                                           :order => 'created_at DESC')
  end
  
  def setup_for_feed
    if self.request.format == :atom
      # Remove page param
      params.delete(:page)
      
      # Set page title
      @feed_title = "#{SITE_NAME} - Site Announcements"
    end
  end
  
  def authorise
    unless BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, :announcements)
      error_to_back_or_home("You are not allowed to perform this action")
      return false
    end
    
    return true
  end
  
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_breadcrumbs.html.erb
<%

# BioCatalogue: app/views/announcements/_breadcrumbs.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<li><%= link_to 'Announcements', announcements_path -%></li>

<% if ["show", "new", "edit"].include? controller.action_name.downcase -%>
  <li><b>&#187;</b></li>
  
  <% case controller.action_name.to_s; when "show" %>
    <li><span><%= display_name(@announcement) -%></span></li>
  <% when "new" %>
    <li><span>New Announcement</span></li>
  <% when "edit" %>
		<li><%= link_to "#{display_name(@announcement)}", announcement_path(@announcement) -%></li>
		<li><b>&#187;</b></li>
    <li><span>Edit</span></li>
  <% else %>
    <!-- no breadcrumb -->
  <% end %>
<% end %>

app/views/announcements/_form.html.erb
<%

# BioCatalogue: app/views/announcements/_form.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<% if !@announcement.nil? && !@announcement.errors.nil? then %>
    <% @announcement.errors.full_messages.each do |err|  %>
        <%= err %>
    <% end %>
<% end %>
<p>
	<label for="announcement_title">Title</label>
	<br/>
	<%= form.text_field :title, :size => 70 %>
</p>

<p>
	<label for="announcement_body">Body</label>
	<br/>
	<%= form.text_area :body, :style => "width: 700px; height: 500px;" %>
</p>

app/views/announcements/_listing.html.erb
<%

# BioCatalogue: app/views/announcements/_listing.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<div class="listings">
	<% items.each do |announcement| %>
		<div class="listing_item">
			<p class="name">
				<%= link_to(display_name(announcement), announcement_path(announcement)) -%>
			</p>
			
			<p class="detail_simple">
				<span style="vertical-align: middle;">By</span>
				<%= user_link_with_flag(:user => announcement.user) %>
				<span class="ago">
        	(<%= distance_of_time_in_words_to_now(announcement.created_at) -%> ago) 
        </span>
			</p>
			
			<% unless announcement.body.blank? -%>
				<div class="box_annotations" style="margin-top: 1em;">
					<% rounded(annotation_text_item_background_color, "#333", "100%") do %>
						<div class="text">
 <%= annotation_prepare_description(announcement.body, {
:do_strip_tags => true, :truncate_length => 500, :do_autolink => false, :is_markdownable => false }
).html_safe -%>

						</div>
					<% end %>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/announcements/edit.html.erb
<%

# BioCatalogue: app/views/announcements/edit.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<h1>Editing Announcement</h1>

<% if !@announcement.nil? && !@announcement.errors.nil? then %>
    <% @announcement.errors.full_messages.each do |err|  %>
        <%= err %>
    <% end %>
<% end %>

<%=  form_for(:announcement, :url => announcement_path(@announcement), :html => { :method => :put }) do |form| %>
  <%= render :partial => 'form', :object => form %>
  <%= submit_tag 'Update', :disable_with => "Updating..." %>
<% end %>

app/views/announcements/index.html.erb
<%

# BioCatalogue: app/views/announcements/index.html.erb
#
# Copyright (c) 2009-2010, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<h1>
    <%= generic_icon_for(:announcements, 'margin-right: 0.4em;') -%>
		Announcements
		<span class="count_text">(<%= Announcement.count %>)</span>
</h1>

<% if BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, :announcements) %>
    <div class="header_left_bar" style="float: none; position: static;" id="center">
			<span class="actions_button_row">
		         <span class="actions_button">
					<%= link_to(image_tag(icon_filename_for(:add)) + content_tag(:span, ' Make an announcement'), new_announcement_path) -%>
				</span>
			</span>
    </div>
<% end %>

<%= render :partial => 'widgets/pagination_top', :locals => { :paginated_items => @announcements } %>

<div id="latest_announcements" style="margin: 1.5em 0;">
	<%= render :partial => "listing", :locals => { :items => @announcements } %>
</div>

<%= render :partial => 'widgets/pagination_bottom', :locals => { :paginated_items => @announcements } %>

app/views/announcements/new.html.erb
<%

# BioCatalogue: app/views/announcements/news.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<h1>New Announcement</h1>

<% if !@announcement.nil? && !@announcement.errors.nil? then %>
    <% @announcement.errors.full_messages.each do |err| %>
        <%= err unless err.nil? %>
    <% end %>
<% end %>

<%= form_for :announcement, :url => announcements_path do |form| -%>
  <%= render :partial => 'form', :object => form %>
  <%= submit_tag "Create", :disable_with => "Creating..." %>
<% end -%>

app/views/announcements/show.html.erb
<%

# BioCatalogue: app/views/announcements/show.html.erb
#
# Copyright (c) 2009-2010, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<% t "#{display_name(@announcement)}" -%>

<h1>
  <div class="resource_title">
    <%= generic_icon_for(:announcements, 'margin-right: 0.4em;') -%>
    Announcement
  </div>
</h1>

<% if BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, :announcements) %>
    <div class="header_left_bar" style="float: none; position: static;" id="center">
        <span class="actions_button_row">
          <span class="actions_button">
                <%= link_to(image_tag(icon_filename_for(:edit)) + content_tag(:span, ' Edit'),
                            edit_announcement_path(@announcement)) -%>
          </span>
          <span class="actions_button">
            <%= link_to(image_tag(icon_filename_for(:delete)) + content_tag(:span, ' Delete'),
                    announcement_path(@announcement),
                    :method => :delete,
                    :confirm => "Are you sure you want to delete this announcement?") -%>
            </span>
	    </span>
    </div>
<% end %>

<div class="message_box">
	<div>
		<p class="subject">
			<%= display_name(@announcement) %>
		</p>
		
		<div style="padding-left: 1.5em;">
			<p><b>By: </b><%= user_link_with_flag(:user => @announcement.user) -%></p>
			<p><b>Created: </b><%= datetime @announcement.created_at -%></p>
		</div>
	</div>
	
	<div class="message">
		<%= annotation_prepare_description(@announcement.body) -%>
	</div>
</div>