config/routes.rb
  match '/curation/elixir_curation' => 'curation#elixir_curation', :as => :elixir_curation, :via => :get

  match '/api.:format' => 'api#show', :as => :api
  match '/lookup.:format' => 'lookup#show', :as => :lookup
  match '/lookup' => 'lookup#show', :as => :lookup
=begin

  match '/wms_services/test' => 'wms_services#test'
=end

  resources :announcements

  resources :service_tests do

    member do
      get :results
      put :enable
      put :disable
      post :new_url_monitor_popup
      post :create_monitoring_endpoint
      post :edit_monitoring_endpoint_by_popup
      post :update_monitoring_endpoint
    end

  end

  resources :test_results

  resources :test_scripts do

    member do
      get :download
    end

  end

  match '/fail/:http_code' => 'fail#index', :as => :fail_page
  match '/stats' => 'stats#index', :as => :stats_index
  match '/stats/refresh' => 'stats#refresh', :as => :refresh_stats, :via => :post

  resources :stats do

    collection do
      get :general
      get :metadata
      get :tags
      get :search
    end
  end

  resources :categories do

    member do
      get :services
    end

  end

  resources :registries do

    member do
      get :annotations_by
      get :services
    end

  end

  resources :agents do

    member do
      get :annotations_by
    end

  end

  resources :annotations do

    collection do
      post :create_multiple
      post :new_popup
      post :create_inline
      post :filtered_index
      get :filters
      post :bulk_create
    end

    member do
      post :edit_popup
      post :promote_alternative_name
      get :download
    end

  end

  resources :annotation_attributes do

    member do
      get :annotations
    end

  end

  resources :tags, :only => [:index, :show, :destroy] do

    collection do
      delete :destroy_taggings
      post :auto_complete
    end


  end

  match '/search/auto_complete' => 'search#auto_complete', :as => :search_auto_complete, :via => :post
  match '/search/ignore_last' => 'search#ignore_last', :as => :ignore_last_search, :via => :post
  match '/search.:format' => 'search#show', :as => :search, :via => [:get, :post]
  match '/search' => 'search#show', :as => :search, :via => [:get, :post]
  match '/search/by_data.:format' => 'search#by_data', :as => :search_by_data, :via => [:get, :post]
  match '/search/by_data' => 'search#by_data', :as => :search_by_data, :via => [:post, :get]



  resources :service_providers do

    collection do
      post :filtered_index
      get :filters
      post :edit_by_popup
      post :auto_complete
    end

    member do
      get :annotations_by
      get :annotations
      get :services
      post :edit_by_popup
      put :upload_logo
      delete :remove_logo

      #for loading tab partials
      get :hostnames
      get :profile
      get :services
    end

  end

  resources :service_provider_hostnames do
    collection do
      post :reassign_provider_by_popup
      post :reassign_provider
    end
  end

  resources :service_deployments do

    member do
      get :annotations
      post :edit_location_by_popup
      post :update_location
    end

  end

  resources :users do

    collection do
      get :whoami
      get :activate_account
      post :filtered_index
      get :rpx_merge_setup
      get :filters
      post :rpx_merge
    end

    member do
      put :remove_curator
      get :annotations_by
      put :deactivate
      get :change_password
      post :change_password
      get :favourites
      get :rpx_update
      post :rpx_update
      put :activate
      get :services_responsible
      get :services_annotated
      get :services_submitted
      get :service_status_notifications
      get :service_status
      get :saved_searches
      get :services
      put :make_curator
    end

  end

  match '/termsofuse' => 'termsofuse#index'

  match '/session' => 'sessions#create', :as => :session, :via => :post

  if ENABLE_RPX
    match '/session/rpx_token' => 'sessions#rpx_token', :as => :session_rpx_token
  end

  match '/register' => 'users#new', :as => :register
  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/signin' => 'sessions#new', :as => :signin
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/activate_account/:security_token' => 'users#activate_account', :as => :activate_account, :security_token => nil
  match '/forgot_password' => 'users#forgot_password', :as => :forgot_password
  match '/request_reset_password' => 'users#request_reset_password', :as => :request_reset_password
  match '/reset_password/:security_token' => 'users#reset_password', :as => :reset_password, :security_token => nil
  match '/contact' => 'contact#create', :as => :submit_feedback, :via => :post
  match '/contact' => 'contact#index', :as => :contact, :via => :get
  match '/' => 'home#index', :as => :home
  match '/index.:format' => 'home#index', :as => :activity_feed
  match '/status_changes.:format' => 'home#status_changes', :as => :status_changes_feed

  match '/latest' => 'latest#show', :as => :latest
  match 'service_providers/auto_complete' => 'service_providers#auto_complete', :as => :service_provider_auto_complete, :via => :post


  resources :latest do
    collection do
      get :activity
      get :monitoring
      get :contributors
      get :services
    end
  end

  resources :rest_services do

    member do
      get :methods
      get :annotations
      get :deployments
      get :resources
      post :edit_base_endpoint_by_popup
    end

    collection do
      post :update_base_endpoint
      get :edit_base_endpoint_by_popup
    end

  end
  
 resources :wms_services do

    collection do
      get :methods
      get :test
    end

  end

  resources :rest_resources do

    member do
      get :methods
      get :annotations
    end

    collection do
      post :new_popup
      post :add_new_resources
    end

  end

  resources :rest_methods do

    collection do
      post :filtered_index
      get :filters
    end

    member do
      post :update_group_name
      post :group_name_auto_complete
      get :inputs
      get :outputs
      get :annotations
      post :inline_add_endpoint_name
      post :edit_group_name_popup
      post :update_resource_path
      put :remove_endpoint_name
      post :edit_endpoint_name_popup
      post :edit_resource_path_popup
      post :update_endpoint_name
    end

  end

  resources :rest_parameters do

    member do
      get :annotations
      post :inline_add_default_value
      put :make_optional_or_mandatory
      post :update_constrained_options
      put :remove_default_value
      get :remove_constrained_options
      post :update_default_value
      post :edit_constrained_options_popup
      post :edit_default_value_popup
      get :localise_globalise_parameter
    end

    collection do
      get :add_new_parameters
      post :add_new_parameters
      post :new_popup
    end

  end

  resources :rest_method_parameters

  resources :rest_representations do

    member do
      get :annotations
    end

    collection do
      post :add_new_representations
      post :new_popup
    end

  end

  resources :rest_method_representations

  resources :soap_services do

    collection do
      post :load_wsdl
      get :load_wsdl
      get :bulk_new
      get :wsdl_locations
    end

    member do
      get :operations
      get :annotations
      get :latest_wsdl
      get :deployments
    end

  end

  resources :soap_operations do

    collection do
      post :filtered_index
      get :filters
    end

    member do
      get :inputs
      get :outputs
      get :annotations
    end

  end

  resources :soap_inputs do

    member do
      get :annotations
    end

  end

  resources :soap_outputs do

    member do
      get :annotations
    end

  end

  resources :soaplab_servers do
    collection do
      post :load_wsdl
    end


  end

  resources :services do

    collection do
      post :filtered_index
      get :filters
      get :bmb
    end

    member do
      post :unarchive
      post :unfavourite
      post :favourite
      get :variants
      get :monitoring
      get :examples
      get :activity
      get :summary
      post :archive
      get :annotations
      post :categorise
      get :deployments
      post :check_updates
      get :service_endpoint
      get :example_scripts
      get :example_data
      get :example_workflows
    end

  end

  resources :responsibility_requests do

    member do
      put :cancel
      get :turn_down
      put :approve
      put :deny
    end

  end

  resources :service_responsibles do

    member do
      put :deactivate
      put :activate
    end

  end

  resources :saved_searches

  # Routes for the favourites plugin
  resources :favourites
  # Old Rails 2 route for favourites:
  # Favourites.map_routes(map)

  # Routes for the annotations plugin
  resources :annotations do

    collection do
      get :filters
      post :new_popup, :create_inline, :filtered_index, :bulk_create
    end

    member do
      get :download
      post :edit_popup, :promote_alternative_name
    end
  end
  # Old Rails 2 route for annotations:
  # Annotations.map_routes(map,
  #                       { :new_popup => :post,
  #                         :create_inline => :post,
  #                         :filters => :get,
  #                         :filtered_index => :post,
  #                         :bulk_create => :post },
  #                       { :edit_popup => :post,
  #                         :download => :get,
  #                         :promote_alternative_name => :post })


  # Route to old metal "alive" now in app/controllers/alive_controller.rb
  match '/alive' => 'alive#index'

  # Replaced with root :to => 'home#index' as we use root_url and root_path in the code
  #match '/' => 'home#index'
  root :to => 'home#index'

app/controllers/home_controller.rb
# BioCatalogue: app/controllers/home_controller.rb
#
# Copyright (c) 2008-2010, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details.

class HomeController < ApplicationController
  
  before_filter :disable_action_for_api, :except => [ :index, :status_changes ]

  def index
    unless is_api_request?
      ActivityLog.benchmark "ActivityLog entries for /home", :level => :info, :silence => false do
        @activity_logs_main = BioCatalogue::ActivityFeeds.activity_logs_for(:home, :style => :simple)
        @activity_logs_monitoring = BioCatalogue::ActivityFeeds.activity_logs_for(:monitoring, :style => :simple, :items_limit => 5)
      end
    end
    
    if self.request.format == :atom
      @feed_title = "#{SITE_NAME} - Latest Activity"
      @activity_logs = BioCatalogue::ActivityFeeds.activity_logs_for(:home, :style => :detailed)
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml { redirect_to api_url(:format => :xml), :status => 303 }
      format.json { redirect_to api_url(:format => :json), :status => 303 }
      format.atom # index.atom.builder
    end
  end
  
  def latest
    unless is_api_request?
      ActivityLog.benchmark "ActivityLog entries for /home/latest", :level => :info, :silence => true do
        @activity_logs_main = BioCatalogue::ActivityFeeds.activity_logs_for(:home, :style => :detailed)
        @activity_logs_monitoring = BioCatalogue::ActivityFeeds.activity_logs_for(:monitoring, :style => :detailed)
      end
    end

    respond_to do |format|
      format.html # latest.html.erb
    end
  end
  
  def status_changes
    if self.request.format == :atom
      @feed_title = "#{SITE_NAME} - Service Monitoring Test Status Changes"
      @activity_logs = BioCatalogue::ActivityFeeds.activity_logs_for(:monitoring, :style => :detailed)
    end
    
    respond_to do |format|
      format.atom # status_changes.atom.builder
    end
  end
  
end

app/helpers/home_helper.rb
# BioCatalogue: app/helpers/home_helper.rb
#
# Copyright (c) 2008, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details.

module HomeHelper
end

app/views/home/_breadcrumbs.html.erb
<%

# BioCatalogue: app/views/home/_breadcrumbs.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<% case controller.action_name.to_s; when "latest" %>
  <li><span><%= link_to "Latest", latest_url -%></span></li>
<% else %>
  <!-- no breadcrumb -->
<% end %>

app/views/home/_fallback_content.html.erb
<%

# BioCatalogue: app/views/home/_fallback_content.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<div id="home_content" style="width: 900px; margin: 0 auto;">

  <div style="float: right; width: 600px;">

    <div style="width: 550px; margin: auto; margin-top: 0.5em;">
			<p class="home_heading"><%= SITE_NAME -%>: providing a curated catalogue<br />of Biodiversity Web Services.</p>
      <div id="div-centered">
      	<% rounded nil, "#333", "auto" do %>
          <%= SITE_NAME -%> currently has
				  <strong><%= link_to pluralize(Service.count, "service"), services_path -%></strong> and
				  <strong><%= link_to pluralize(User.count_activated, "member"), users_url -%></strong>
					<%= info_icon_with_tooltip("<b>Members</b> are registered users of #{SITE_NAME}.<br/><br/>If you would like to sign up for an account and become a member please click on 'Sign Up' towards the top right. <br/><br/>#{sign_up_benefits_text}") -%>
				<% end %>
      </div>
    </div>

    <div class="liquid-round" style="width: 500px; margin-top: 3em;">
      <div class="top"><span></span></div>
      <div class="center-content">
				<!-- CONTENT BEGIN -->
				<img class="round_box_title" src="/assets/search_title.gif" alt="Search for Web Services" />
				<p>
				  The easiest way to <em>find the Web Service</em> you are looking for is to use the <%= SITE_NAME -%>
				  search functionality below (also available in the action bar at the top of every page).
				</p>
				<p>
				  <div class="search_widget">
				    <%= form_tag search_url, :method => :get do %>
					    <b>Search:</b>
							<%= text_field_tag :q, params[:q], :id => "home_search_field", :size => 40, :autocomplete => "off" -%>
							
							<div class="auto_complete" id="home_search_auto_complete"></div>
							
							<%= auto_complete_field "home_search_field",
									:update => "home_search_auto_complete",
									:url => search_auto_complete_url,
									:min_chars => 3 -%>
									
					    <%= submit_tag '', :class => "search_button" -%>
				    <% end %>
				  </div>
				</p>
				<!-- CONTENT END -->
      </div>
      <div class="bottom"><span></span></div>
    </div>

    <div style="width: 550px; margin: auto;">
      <h2>Our goals:</h2>
      <ul id="key_points">
				<li>Providing a <em>single registration point</em> for Web Service providers
				  and a <em>single search site</em> for scientists and developers.</li>
				<li>Providers, Expert curators and Users will provide oversight, monitor the catalogue 
				  and provide <em>high quality annotations</em> for services.</li>
				<li><%= SITE_NAME -%> is a place where the <em>community</em> can find contacts and meet
				  the experts and maintainers of these services.</li>
      </ul>
    </div>

  </div>

  <div style="float:left; width:270px;">

    <div class="liquid-round" style="width: 260px;">
      <div class="top"><span></span></div>
      <div class="center-content" style="height: 14.5em;">
				<!-- CONTENT BEGIN -->
				<img class="round_box_title" src="/assets/browse_title.gif" alt="Browse all Web Services" />
				<p>
				  You can have an overview of the content of the <%= SITE_NAME -%> by <em>browsing our registry</em> and
				  sorting or filtering down the list of Web Services registered.
				</p>
				<div class="center" style="height: 70px;">
				  <%= link_to image_tag("browse_web_services_button.png", :alt => "Browse Web Services"), services_path %>
				</div>
				<!-- CONTENT END -->
      </div>
      <div class="bottom"><span></span></div>
    </div>

    <div class="liquid-round" style="width: 260px; margin-top: 3em;">
      <div class="top"><span></span></div>
      <div class="center-content" style="height: 16em;">
				<!-- CONTENT BEGIN -->
				<img class="round_box_title" src="/assets/register_title.gif" alt="Register a Web Services" />
				<p>
				  You can easily <em>register Web Services</em> in the <%= SITE_NAME -%>, making them instantly available
				  to the scientific community as well as the tool developers.
				</p>
				<div class="center">
				  <%= link_to image_tag("register_web_services_button.png", :alt => "Register Web Services"), new_service_path %>
				</div>
				<br />
				<p style="font-size: 85%;">
				  To register a Web Service you will need to <%= link_to 'sign in', "/login", :id => "login_link", :class => "login" -%> first.
				</p>
				<!-- CONTENT END -->
      </div>
      <div class="bottom"><span></span></div>
    </div>
  </div>

</div>

app/views/home/_info_boxes.html.erb
<%

# BioCatalogue: app/views/home/_info_boxes.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<div style="width: 470px; margin: 0 auto;">

	<!-- DISCOVER -->
	<div class="liquid-round" style="width: 230px; margin-bottom: 5px; float: left; margin-right: 10px;">
	  <div class="top"><span></span></div>
	  <div class="center-content" style="height: 12em;">
			<!-- CONTENT BEGIN -->
			<p class="info_text_head">
			  "Web Services are hard to find"
			</p>
			<p class="info_text_label">
				<%= link_to(image_tag("label_discover.png", :alt => "Discover Services"), services_path) -%>
			</p>
			<ul class="info_text_list">
				<li>
					Find the right Web Service
				</li>
				<li>
					Powerful search and filtering
				</li>
				<li>
					Information from providers and community
				</li>
			</ul>
			<p style="text-align: center; margin-top: 0.5em;">
				<b><%= link_to "More info", "http://www.biocatalogue.org/wiki/doku.php?id=public:help:biocatalogue:discovering_web_services", :target => "_blank" -%></b>
			</p>
			<!-- CONTENT END -->
	  </div>
	  <div class="bottom"><span></span></div>
	</div>
	
	<!-- REGISTER -->
	<div class="liquid-round" style="width: 230px; margin-bottom: 5px; float: left;">
	  <div class="top"><span></span></div>
	  <div class="center-content" style="height: 12em;">
			<!-- CONTENT BEGIN -->
			<p class="info_text_head">
			  "My Web Services are not visible"
			</p>
			<p class="info_text_label">
				<%= link_to(image_tag("label_register.png", :alt => "Register Services"), new_service_path) -%>
			</p>
			<ul class="info_text_list">
				<li>
					Easily register Web Services
				</li>
				<li>
					Instantly available to everyone
				</li>
				<li>
					Providers can advertise, describe and monitor their Services
				</li>
			</ul>
			<p style="text-align: center; margin-top: 0.5em;">
				<b><%= link_to "More info", "http://www.biocatalogue.org/wiki/doku.php?id=public:help:biocatalogue:registering_web_services", :target => "_blank" -%></b>
			</p>
			<!-- CONTENT END -->
	  </div>
	  <div class="bottom"><span></span></div>
	</div>
	
	<span class="clear"></span>

</div>

<div style="width: 470px; margin: 0 auto;">

	<!-- ANNOTATE -->
	<div class="liquid-round" style="width: 230px; margin-bottom: 20px; float: left; margin-right: 10px;">
	  <div class="top"><span></span></div>
	  <div class="center-content" style="height: 10.5em;">
			<!-- CONTENT BEGIN -->
			<p class="info_text_head">
			  "Web Services are poorly described"
			</p>
			<p class="info_text_label">
				<%= image_tag "label_annotate.png" -%>
			</p>
			<ul class="info_text_list">
				<li>
					Anyone can describe and annotate
				</li>
				<li>
					Ongoing expert curation
				</li>
				<li>
					Social curation by the community
				</li>
			</ul>
			<p style="text-align: center; margin-top: 0.5em;">
				<b><%= link_to "More info", "http://www.biocatalogue.org/wiki/doku.php?id=public:help:biocatalogue:annotating_web_services", :target => "_blank" -%></b>
			</p>
			<!-- CONTENT END -->
	  </div>
	  <div class="bottom"><span></span></div>
	</div>
	
	<!-- MONITOR -->
	<div class="liquid-round" style="width: 230px; margin-bottom: 20px; float: left;">
	  <div class="top"><span></span></div>
	  <div class="center-content" style="height: 10.5em;">
			<!-- CONTENT BEGIN -->
			<p class="info_text_head">
			  "Web Services are volatile"
			</p>
			<p class="info_text_label">
				<%= image_tag "label_monitor.png" -%>
			</p>
			<ul class="info_text_list">		
				<li>
					Services change and get outdated
				</li>
				<li>
					<%= SITE_NAME -%> monitors Services
				</li>
				<li>
					 Monitors availability and reliability
				</li>
			</ul>
			<p style="text-align: center; margin-top: 0.5em;">
				<b><%= link_to "More info", "http://www.biocatalogue.org/wiki/doku.php?id=public:help:biocatalogue:how_we_monitor_web_services", :target => "_blank" -%></b>
			</p>
			<!-- CONTENT END -->
	  </div>
	  <div class="bottom"><span></span></div>
	</div>

	<span class="clear"></span>

</div>

app/views/home/fallback.html.erb
<%

# BioCatalogue: app/views/home/fallback.html.erb
#
# Copyright (c) 2009-2010, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<%= render :partial => "home/fallback_content" -%>

app/views/home/index.html.erb
<%

# BioCatalogue: app/views/home/index.html.erb
#
# Copyright (c) 2008-2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<div id="home_content">
	
	<p id="home_heading">The <%= SITE_NAME -%>: providing a curated catalogue of life science Web services</p>
	
	<div id="middle_column_wrapper">
		<div id="middle_column">
			
			<div id="home_stats_bar">
		    <div id="div-centered" style="width: 100%;">
		    	<% rounded nil, "#333", "100%" do %>
            <%= SITE_NAME -%> currently has
					  <strong><%= link_to pluralize(Service.not_archived.count, "service"), services_path -%></strong>,
						<strong><%= link_to pluralize(ServiceProvider.count, "service provider"), service_providers_path -%></strong> and
					  <strong><%= link_to pluralize(User.count_activated, "member"), users_url -%></strong>
						<%= info_icon_with_tooltip("<b>Members</b> are registered users of #{SITE_NAME}.<br/><br/>If you would like to sign up for an account and become a member please click on 'Sign Up' towards the top right. <br/><br/>#{sign_up_benefits_text}") -%>
					<% end %>
		    </div>
		  </div>
			
			<%= render :partial => "home/info_boxes" -%>
			
			<% if false %>
			<div style="width: 470px; margin: 0 auto; margin-top: 1em;">
				<h3>Our Goals</h3>
		    <ul id="key_points">
					<li>Providing a <em>single registration point</em> for Web Service providers
					  and a <em>single search site</em> for scientists and developers.</li>
					<li>Providers, Expert curators and Users will provide oversight, monitor the catalogue 
					  and provide <em>high quality annotations</em> for services.</li>
					<li><%= SITE_NAME -%> is a place where the <em>community</em> can find contacts and meet
					  the experts and maintainers of these services.</li>
		    </ul>
			</div>
			<% end %>
		</div>
	</div>
	
	<div id="left_column">
		<div class="column_inner">

          <!-- Helpful Links -->
          <div class="section_box">
            <h4>
              <%= generic_icon_for(:info, 'margin-right: 0.4em;') -%>
              <span>Helpful Links</span>
            </h4>

            <div class="section_content" style="font-size: 85%;">
              <p>
                <a href="http://www.biocatalogue.org/wiki/doku.php?id=public:help:getting_started" target="_blank">Getting started with the Catalogue</a>
              </p>
              <p>
                <a href="http://www.biocatalogue.org/wiki/doku.php?id=public:help:general_info_on_web_services" target="_blank">General info on Web services</a>
              </p>
              <p>
                <a href="http://dev.mygrid.org.uk/wiki/display/scrap/Web+services+guidelines" target="_blank">Best practice guide for developing Web services</a>
              </p>
              <p>
                <a href="http://www.software.ac.uk/blog/2013-12-04-top-tips-creating-web-services" target="_blank">SSI's top tips on creating Web services</a>
              </p>
              <p>
                <a href="http://www.biocatalogue.org/wiki/doku.php?id=public:help:executing_web_services" target="_blank">Executing Web services</a>
              </p>
              <p>
                <a href="http://soaplab.sourceforge.net/soaplab2/StepByStep.html" target="_blank">Turn your command line application(s) into Web services</a>
              </p>
            </div>
          </div>

          <div class="section_box">
            <h4>
              <%= generic_icon_for(:info, 'margin-right: 0.4em;') -%>
              <span>Citing BioCatalogue</span>
            </h4>

            <div class="section_content" style="font-size: 85%;">
              <p>Bhagat, J., Tanoh, F., Nzuobontane, E., Laurent, T., Orlowski, J., Roos, M., Wolstencroft, K., Aleksejevs, S., Stevens, R., Pettifer, S., Lopez, R., Goble, C.A.</p>
              <p><i><a href="http://dx.doi.org/10.1093/nar/gkq394">BioCatalogue: a universal catalogue of web services for the life sciences</a></i></p>
              <p>Nucl. Acids Res. (2010) 38: 689-694 <br> doi:10.1093/nar/gkq394</p>
            </div>
            </div>
		</div>
	</div>
	
	<div id="right_column">
		<div class="column_inner">
			
			<!-- Site Announcements -->
			<div class="section_box">
				<h4>
					<span style="float: right; margin-left: 0.3em;">
						<%= feed_icon_tag "Site Announcements", announcements_path(:format => :atom) -%>
					</span>
					<%= generic_icon_for(:announcements, 'margin-right: 0.4em;') -%>
					<span>Site Announcements</span>
				</h4>
				
				<div class="section_content" style="font-size: 85%;">
					<% unless (announcements = Announcement.latest(5)).empty? %>
						<% announcements.each do |a| %>
							<p style="margin-bottom: 0.7em;">
								<b><%= link_to display_name(a), a -%></b>
								<br/>
								By <%= link_to display_name(a.user), a.user -%>
								<span class="ago">(<%= distance_of_time_in_words_to_now(a.created_at) -%> ago)</span>
							</p>
						<% end %>
					<% else %>
						<p class="none_text">None</p>
					<% end %>
				</div>
				
				<div class="section_footer">
					<% if BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, :announcements) %>
						<b><%= link_to "New", new_announcement_url %></b>
						|
					<% end %>
					<b><%= link_to "More", announcements_url %></b>
				</div>
			</div>
		</div>
	</div>
		
	<span class="clear"></span>
</div>

app/views/home/latest.html.erb
<%

# BioCatalogue: app/views/home/latest.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<h1>Latest in <%= SITE_NAME -%></h1>


<div id="home-tabs" class="tabberlive">

<%= tabs_tag(:builder => MenuTabBuilder, :namespace => :latest) do |tab| %>
    <%= tab.activity            'Activity', activity_latest_index_path %>
    <%= tab.monitoring          'Monitoring', monitoring_latest_index_path %>
    <%= tab.services            'Services', services_latest_index_path %>
    <%= tab.contributors        'Contributors', contributors_latest_index_path %>

<% end %>

  <% current_tab(:latest).to_s %>
  <% case current_tab(:latest).to_s %>
  <% when 'activity' %>
      <%= render :partial => "home/latest_tabs/tab_activity" %>
  <% when 'contributors' %>
      <%= render :partial => "home/latest_tabs/tab_contributors" %>
  <% when 'monitoring' %>
      <%= render :partial => "home/latest_tabs/tab_monitoring" %>
  <% when 'services' %>
      <%= render :partial => "home/latest_tabs/tab_services" %>
  <% else %>
      <%= render :partial => "home/latest_tabs/tab_activity" %>
  <% end %>
</div>