config/routes.rb
  get "wms_representations/get_redirect_url"

  get "wms_representations/destroy_method_rep_map"

  get "wms_resources/new_popup"

  get "wms_resources/add_new_resources"

  get "wms_resources/index"

  get "wms_resources/show"

  get "wms_resources/annotations"

  get "wms_resources/methods"

  get "wms_resources/parse_sort_params"

  get "wms_resources/authorise"

  get "wms_resources/find_wms_service"

  get "wms_resources/find_wms_resource"
=begin

  get "wms_services/new"

  get "wms_services/edit"

=end
 # get "wms_services/test"

  resources :oauth_clients

  match '/oauth/test_request' => 'oauth#test_request', :as => :test_request
  match '/oauth/access_token' => 'oauth#access_token', :as => :access_token
  match '/oauth/request_token' => 'oauth#request_token', :as => :request_token
  match '/oauth/authorize' => 'oauth#authorize', :as => :authorize
  match '/oauth' => 'oauth#index', :as => :oauth
  match '/curation' => 'curation#show', :as => :curation, :via => :get
  match '/curation/reports/potential_duplicate_operations_within_service' => 'curation#potential_duplicate_operations_within_service', :as => :curation_reports_potential_duplicate_operations_within_service, :via => :get
  match '/curation/reports/providers_without_services' => 'curation#providers_without_services', :as => :curation_reports_providers_without_services, :via => :get
  match '/curation/reports/services_missing_annotations' => 'curation#services_missing_annotations', :as => :curation_reports_services_missing_annotations, :via => [:get, :post]
  match '/curation/tools/copy_annotations' => 'curation#copy_annotations', :as => :curation_tools_copy_annotations, :via => [:get, :post]
  match '/curation/tools/copy_annotations_preview' => 'curation#copy_annotations_preview', :as => :curation_tools_copy_annotations_preview, :via => :post
  match '/curation/reports/annotation_level' => 'curation#annotation_level', :as => :curation_annotation_level, :via => :get
  match '/curation/reports/links_checker' => 'curation#links_checker', :as => :link_checker, :via => :get
  match '/curation/tools/download_latest_csv' => 'curation#download_latest_csv', :as => :download_latest_csv, :via => :get
  match '/curation/tools/csv_export' => 'curation#download_csv_page', :as => :download_csv_page, :via => :get
  match '/curation/elixir_curation' => 'curation#elixir_curation', :as => :elixir_curation, :via => :get

  match '/api.:format' => 'api#show', :as => :api
  match '/lookup.:format' => 'lookup#show', :as => :lookup
  match '/lookup' => 'lookup#show', :as => :lookup
=begin

  match '/wms_services/test' => 'wms_services#test'
=end

  resources :announcements

  resources :service_tests do

    member do
      get :results
      put :enable
      put :disable
      post :new_url_monitor_popup
      post :create_monitoring_endpoint
      post :edit_monitoring_endpoint_by_popup
      post :update_monitoring_endpoint
    end

  end

  resources :test_results

  resources :test_scripts do

    member do
      get :download
    end

  end

  match '/fail/:http_code' => 'fail#index', :as => :fail_page
  match '/stats' => 'stats#index', :as => :stats_index
  match '/stats/refresh' => 'stats#refresh', :as => :refresh_stats, :via => :post

  resources :stats do

    collection do
      get :general
      get :metadata
      get :tags
      get :search
    end
  end

  resources :categories do

    member do
      get :services
    end

  end

  resources :registries do

    member do
      get :annotations_by
      get :services
    end

  end

  resources :agents do

    member do
      get :annotations_by
    end

  end

  resources :annotations do

    collection do
      post :create_multiple
      post :new_popup
      post :create_inline
      post :filtered_index
      get :filters
      post :bulk_create
    end

    member do
      post :edit_popup
      post :promote_alternative_name
      get :download
    end

  end

  resources :annotation_attributes do

    member do
      get :annotations
    end

  end

  resources :tags, :only => [:index, :show, :destroy] do

    collection do
      delete :destroy_taggings
      post :auto_complete
    end


  end

  match '/search/auto_complete' => 'search#auto_complete', :as => :search_auto_complete, :via => :post
  match '/search/ignore_last' => 'search#ignore_last', :as => :ignore_last_search, :via => :post
  match '/search.:format' => 'search#show', :as => :search, :via => [:get, :post]
  match '/search' => 'search#show', :as => :search, :via => [:get, :post]
  match '/search/by_data.:format' => 'search#by_data', :as => :search_by_data, :via => [:get, :post]
  match '/search/by_data' => 'search#by_data', :as => :search_by_data, :via => [:post, :get]



  resources :service_providers do

    collection do
      post :filtered_index
      get :filters
      post :edit_by_popup
      post :auto_complete
    end

    member do
      get :annotations_by
      get :annotations
      get :services
      post :edit_by_popup
      put :upload_logo
      delete :remove_logo

      #for loading tab partials
      get :hostnames
      get :profile
      get :services
    end

  end

  resources :service_provider_hostnames do
    collection do
      post :reassign_provider_by_popup
      post :reassign_provider
    end
  end

  resources :service_deployments do

    member do
      get :annotations
      post :edit_location_by_popup
      post :update_location
    end

  end

  resources :users do

    collection do
      get :whoami
      get :activate_account
      post :filtered_index
      get :rpx_merge_setup
      get :filters
      post :rpx_merge
    end

    member do
      put :remove_curator
      get :annotations_by
      put :deactivate
      get :change_password
      post :change_password
      get :favourites
      get :rpx_update
      post :rpx_update
      put :activate
      get :services_responsible
      get :services_annotated
      get :services_submitted
      get :service_status_notifications
      get :service_status
      get :saved_searches
      get :services
      put :make_curator
    end

  end

  match '/termsofuse' => 'termsofuse#index'

  match '/session' => 'sessions#create', :as => :session, :via => :post

  if ENABLE_RPX
    match '/session/rpx_token' => 'sessions#rpx_token', :as => :session_rpx_token
  end

  match '/register' => 'users#new', :as => :register
  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/signin' => 'sessions#new', :as => :signin
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/activate_account/:security_token' => 'users#activate_account', :as => :activate_account, :security_token => nil
  match '/forgot_password' => 'users#forgot_password', :as => :forgot_password
  match '/request_reset_password' => 'users#request_reset_password', :as => :request_reset_password
  match '/reset_password/:security_token' => 'users#reset_password', :as => :reset_password, :security_token => nil
  match '/contact' => 'contact#create', :as => :submit_feedback, :via => :post
  match '/contact' => 'contact#index', :as => :contact, :via => :get
  match '/' => 'home#index', :as => :home
  match '/index.:format' => 'home#index', :as => :activity_feed
  match '/status_changes.:format' => 'home#status_changes', :as => :status_changes_feed

  match '/latest' => 'latest#show', :as => :latest
  match 'service_providers/auto_complete' => 'service_providers#auto_complete', :as => :service_provider_auto_complete, :via => :post


  resources :latest do
    collection do
      get :activity
      get :monitoring
      get :contributors
      get :services
    end
  end

  resources :rest_services do

    member do
      get :methods
      get :annotations
      get :deployments
      get :resources
      post :edit_base_endpoint_by_popup
    end

    collection do
      post :update_base_endpoint
      get :edit_base_endpoint_by_popup
    end

  end
  
 resources :wms_services do

    collection do
      get :methods
      get :test
    end

  end

  resources :rest_resources do

    member do
      get :methods
      get :annotations
    end

    collection do
      post :new_popup
      post :add_new_resources
    end

  end

  resources :rest_methods do

    collection do
      post :filtered_index
      get :filters
    end

    member do
      post :update_group_name
      post :group_name_auto_complete
      get :inputs
      get :outputs
      get :annotations
      post :inline_add_endpoint_name
      post :edit_group_name_popup
      post :update_resource_path
      put :remove_endpoint_name
      post :edit_endpoint_name_popup
      post :edit_resource_path_popup
      post :update_endpoint_name
    end

  end

  resources :rest_parameters do

    member do
      get :annotations
      post :inline_add_default_value
      put :make_optional_or_mandatory
      post :update_constrained_options
      put :remove_default_value
      get :remove_constrained_options
      post :update_default_value
      post :edit_constrained_options_popup
      post :edit_default_value_popup
      get :localise_globalise_parameter
    end

    collection do
      get :add_new_parameters
      post :add_new_parameters
      post :new_popup
    end

  end

  resources :rest_method_parameters

  resources :rest_representations do

    member do
      get :annotations
    end

    collection do
      post :add_new_representations
      post :new_popup
    end

  end

  resources :rest_method_representations

  resources :soap_services do

    collection do
      post :load_wsdl
      get :load_wsdl
      get :bulk_new
      get :wsdl_locations
    end

    member do
      get :operations
      get :annotations
      get :latest_wsdl
      get :deployments
    end

  end

  resources :soap_operations do

    collection do
      post :filtered_index
      get :filters
    end

    member do
      get :inputs

app/models/tag.rb
# BioCatalogue: app/models/tag.rb
#
# Copyright (c) 2011, University of Manchester, The European Bioinformatics
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

class Tag < ActiveRecord::Base
  validates_presence_of :name,
                        :label
  
  validates_uniqueness_of :name
  
  acts_as_annotation_value :content_field => :name
  
  if USE_EVENT_LOG
    acts_as_activity_logged
  end
  
  def self.find_or_create_simple_tag(tag_name)
    self.find_or_create_by_name_and_label(tag_name, tag_name)
  end
  
end

app/controllers/tags_controller.rb
# BioCatalogue: app/controllers/tags_controller.rb
#
# Copyright (c) 2008-2011, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details.

class TagsController < ApplicationController
  
  before_filter :disable_action_for_api, :except => [ :index, :show ]
  
  skip_before_filter :verify_authenticity_token, :only => [ :auto_complete ]
  
  before_filter :find_tags, :only => [ :index ]
  before_filter :find_tag, :only => [ :show, :destroy, :destroy_taggings ]
  before_filter :find_tag_results, :only => [ :show ]
  before_filter :get_tag_items_count, :only => [ :show ]
  
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml  # index.xml.builder
      format.json { render :json => BioCatalogue::Api::Json.index("tags", json_api_params, @tags, :total_tags_count => @total_tags_count, :total_pages => @total_pages).to_json }
    end
  end
  
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  # show.xml.builder
      format.json { render :json => BioCatalogue::Api::Json.tag(@tag.name, @tag.label, @total_items_count).to_json }
    end
  end
  
  def auto_complete
    @tag_fragment = '';
    
    if params[:annotations] and params[:annotations][:tags]
      @tag_fragment = params[:annotations][:tags]
    elsif  params[:annotation] and params[:annotation][:value]
      @tag_fragment = params[:annotation][:value]
    end
    
    @tags = BioCatalogue::Tags.get_tag_suggestions(@tag_fragment, 50)
                     
    render :inline => "<%= auto_complete_result @tags, 'name' %>", :layout => false
  end
  
  def destroy
    raise NotImplemented
  end
  
  def destroy_taggings
    annotatable = Annotation.find_annotatable(params[:annotatable_type], params[:annotatable_id])
    
    if !annotatable.nil?
      existing = Annotation.all(
                                 :conditions => { :annotatable_type => annotatable.class.name,
                                                  :annotatable_id => annotatable.id,
                                                  :attribute_id => AnnotationAttribute.find_by_name("tag").id, 
                                                  :value_type => "Tag",
                                                  :value_id => @tag.id })
      
      unless existing.blank?
        existing.each do |a|
          submitters = [ BioCatalogue::Mapper.compound_id_for_model_object(a.source) ]
          if BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, :tag, :tag_submitters => submitters)            
            a.destroy
          end
        end
      end
    end
    
    respond_to do |format|
      format.html { render :partial => 'annotations/tags_box_inner_tag_cloud', 
                           :locals => { :tags => BioCatalogue::Annotations.get_tag_annotations_for_annotatable(annotatable),
                                        :annotatable => annotatable } }
    end
  end
  
protected

  def find_tags
    @sort = params[:sort].try(:to_sym)
    
    if is_api_request?
      @sort = :counts if @sort.blank? or ![ :counts, :name ].include?(@sort)
      @tags = BioCatalogue::Tags.get_tags(:sort => @sort, :page => @page, :per_page => @per_page)
    else
      @sort = :name if @sort.blank? or ![ :counts, :name ].include?(@sort)
      # TODO: check this is the right behaviour and not too bad in terms of performance
      @tags = BioCatalogue::Tags.get_tags(:sort => @sort)
    end
    
    @total_tags_count = BioCatalogue::Tags.get_total_tags_count
    
    # NOTE: there is an assumption here this index has not been 
    # filtered/restricted in any way apart from paging. 
    @total_pages = (@total_tags_count.to_f / @per_page.to_f).ceil
  end
  
  def find_tag
    if action_name == 'destroy_taggings'
      tag_name = params[:tag_name]
    else
      dup_params = BioCatalogue::Util.duplicate_params(params)
      dup_params[:tag_keyword] = dup_params[:id]
      tag_name = BioCatalogue::Tags.get_tag_name_from_params(dup_params)
    end
    @namespace = params[:namespace] || nil
    @tag = Tag.find_by_name(tag_name)

    raise ActiveRecord::RecordNotFound.new if @tag.nil?
  end

  def find_tag_results
    unless is_api_request?
      @service_ids = [ ]

      @include_archived = false
      if !params[:include_archived].nil? && params[:include_archived] == 'true'
        @include_archived = true
      end

      unless @tag.blank?
        @scope = params[:scope]
        @visible_search_type = BioCatalogue::Search.scope_to_visible_search_type(@scope) unless is_api_request?
        @results = { }
        @count = 0
        ids_for_results = BioCatalogue::Tags.get_service_ids_for_tag(@tag.name)
        ids_for_results.each do |scope, values|
          result_models = BioCatalogue::Mapper.item_ids_to_model_objects(values,scope)
          result_models.reject!{|result_model| !@include_archived && (result_model.try(:archived?) || result_model.try(:belongs_to_archived_service?))}
          @results[scope] = result_models unless result_models.nil?

        end
        @results.each_value do |result_scope|
          @count += result_scope.length
        end

        @results
      end
    end
  end
  
  def get_tag_items_count
    unless @tag.blank?
      @total_items_count = BioCatalogue::Tags.get_total_items_count_for_tag_name(@tag.name)
    end
  end
  
end

app/views/tags/_breadcrumbs.html.erb
<%

# BioCatalogue: app/views/tags/_breadcrumbs.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<li><%= link_to 'Tags', tags_path -%></li>

<% if ["show"].include? controller.action_name.downcase -%>
  <li><b>&#187;</b></li>
  
  <% case controller.action_name.to_s; when "show" -%>
    <li><span><%= h(@tag_name) -%></span></li>
  <% else -%>
    <!-- no breadcrumb -->
  <% end -%>
<% end -%>

app/views/tags/index.html.erb
<%

# BioCatalogue: app/views/tags/index.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<% t "All Tags" -%>

<h1 style="text-align: center; margin-bottom: 1em;">
	<span style="vertical-align:middle;">
		Tags Used on <%= SITE_NAME -%> (<%= pluralize(@tags.length, "tag") -%>)
	</span>
	<span style="vertical-align:middle; margin-left:0.5em;">
		<%= help_icon_with_tooltip(help_text_for_tag_clouds) -%>
	</span>
</h1>

<div id="div-centered" style="width: 80%;">
	<%= generate_tag_cloud(@tags, :weighted, :tag_cloud_style => "width: 100%;") %>
</div>

app/views/tags/show.html.erb
<%

# BioCatalogue: app/views/tags/show.html.erb
#
# Copyright (c) 2009, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<% 
	count = @service_ids.length
	
%>

<% t "Results for tag '#{@tag.name}'" -%>

<% if @visible_search_type.blank? %>
    <h1>Tag Results</h1>
<% else %>
    <h1>Tag Results <span class="faded">(<%= @visible_search_type -%> only)</span></h1>
<% end %>

<% unless @scope %>
    <p style="font-size: 123.1%;">
      Tag
      "<b><%= h(@tag.label) -%></b>"
      <% unless @tag.name == @tag.label %>
          (
          <%= @tag.name -%>
          )
      <% end %>
      returned <%= pluralize(@count, "results") -%>
    </p>
<% end %>
<span class="clear"></span>

<div class="search_options" style="margin-top: 40px; margin-right: 10px;">
  <div class="search_option">
            <span style="vertical-align: middle; font-weight: bold;">
            Include archived?
            </span>
            <span style="vertical-align: middle; padding: 0; margin-left: 0.1em; width: 100%;">
                <input type="checkbox"
                       name="include_archived"
                       id="include_archived"
                       data-onchange-url="<%= generate_include_archived_url('tag', !include_archived?) %>"
                       onchange="loadUrlFromCheckboxInputTag(this); return false;"
                       <%= "checked='yes'" if include_archived? %> />
            </span>
  </div>
  <% params_dup = BioCatalogue::Util.duplicate_params(params) %>
  <% params_dup = BioCatalogue::Util.remove_rails_special_params_from(params_dup) %>
  <div class="search_option">
    <%= link_to("Filter services", services_path(:tag => "[#{@tag.name}]", :include_archived => @include_archived || false), :class => "button_slim") %>
  </div>
  <% unless @scope.nil? %>
      <div class="search_option">
        <% if @include_archived %>
            <%= link_to  (image_tag(icon_filename_for(:arrow_backward)) + content_tag(:span, " Back to all results for tag")), tag_path(@tag.label, :include_archived => 'true'), :class => "button_slim" -%>
      <% else %>
            <%= link_to  (image_tag(icon_filename_for(:arrow_backward)) + content_tag(:span, " Back to all results for tag")), tag_path(@tag.label), :class => "button_slim" -%>
      <% end %>
      </div>
  <% end %>
</div>
<% if @results.empty? || @results.blank? %>

    <p class="none_text">No services.</p>

<% else %>
    <div id="search_results" class="tabber">
      <% if @scope.nil? %>
          <% @results.each do |result_scope_string, result_models| %>
              <% result_scope = result_scope_string.to_s.underscore.pluralize %>
              <% visible_result_scope = BioCatalogue::Search.scope_to_visible_search_type(result_scope)
                 items = result_models
                 count = items.length
                 items = items.paginate(:page => @page, :per_page => @per_page)
                 more_items = count > @per_page %>
              <% unless items.empty? %>

                  <div id='<%= "tab-#{result_scope}" -%>' class="tabbertab">
                    <% count_text = more_items ? "#{items.length} of #{count}" : "#{items.length}" %>
                    <h3><%= "#{visible_result_scope} (#{count_text})" -%></h3>

                    <div style="margin: 0 0 1.5em 0;">
                      <% if more_items %>
                          <div style="color: #555;">
                            <%= "Showing the top #{items.length} items out of #{count} in total" -%>
                          </div>
                          <% next_page_parameters = {:page => 2, :scope => result_scope} %>
                          <% next_page_parameters[:include_archived] = @include_archived unless @include_archived.nil? %>
                          <% next_page_parameters[:namespace] = @namespace unless @namespace.nil? %>
                      <% end %>
                      <div style="margin-top: 1em;">
                        <table style="width: 100%;">
                          <tr>
                            <td>
                              <% if more_items %>
                                  <%= link_to(content_tag(:span, "Next page of results ") + image_tag(icon_filename_for(:arrow_forward)),
                                              tag_url(@tag.label,next_page_parameters),
                                              :class => "button_slim") -%>
                              <% end %>
                            </td>
                          </tr>
                        </table>
                      </div>
                    </div>
                    <div style="clear: both;"></div>
                    <%= render :partial => "#{result_scope}/listing", :locals => {:items => items} %>
                    <% if more_items %>
                        <p>
                          <%= link_to(content_tag(:span, "Next page of results ") + image_tag(icon_filename_for(:arrow_forward)),
                                      tag_url(@tag.label,next_page_parameters),
                                      :class => "button_slim") -%>
                        </p>
                    <% end %>
                  </div>
              <% end #unless items.empty?%>
          <% end #each result%>

      <% else %>
          <%  @visible_search_type = @scope.humanize
             result_scope = @scope.singularize.camelize
             items = @results[result_scope]
             count = items.length
             items = items.paginate(:page => @page, :per_page => @per_page)
          %>
          <p> Tags for
            "<b><%= h @tag.label -%></b>"
            returned
            <%= pluralize(count, @visible_search_type.singularize) -%>  </p>
          <%= render :partial => 'widgets/pagination_top', :locals => {:paginated_items => items, :entry_name => @scope.gsub('_', ' ').singularize} %>
          <div id="search_results" style="margin: 2em 0;">
            <%= render :partial => "#{@scope}/listing", :locals => {:items => items} %>
          </div>
          <%= render :partial => 'widgets/pagination_bottom', :locals => {:paginated_items => items} %>
      <% end %>
    </div>
<% end #results empty %>

<br />