config/routes.rb
BioCatalogue::Application.routes.draw do

  #get "wms_service_layer/show"

  get "wms_service_layer/layer"

  get '/wms_service_layer/:id', to: 'wms_service_layer#show'

  get "wms_methods/update_resource_path"

  get "services/test"

  get "wms_methods/edit_resource_path_popup"

  get "wms_methods/update_endpoint_name"

  get "wms_methods/edit_endpoint_name_popup"

  get "wms_methods/update"

  get "wms_methods/edit_by_popup"

  get "wms_methods/remove_endpoint_name"

  get "wms_methods/inline_add_endpoint_name"

  get "wms_methods/index"

  get "wms_methods/filtered_index"

  get "wms_methods/show"

  get "wms_methods/inputs"

  get "wms_methods/outputs"

  get "wms_methods/annotations"

  get "wms_methods/destroy"

  get "wms_methods/edit_group_name_popup"

  get "wms_methods/update_group_name"

  get "wms_methods/group_name_auto_complete"

  get "wms_methods/filters"

  get "wms_methods/authorise"

  get "wms_methods/parse_sort_params"

  get "wms_methods/find_rest_method"

  get "wms_methods/find_rest_methods"

  get "wms_methods/destroy_unused_objects"

  get "wms_parameters/show"

  get "wms_parameters/annotations"

  get "wms_parameters/update_default_value"

  get "wms_parameters/edit_default_value_popup"

  get "wms_parameters/remove_default_value"

  get "wms_parameters/inline_add_default_value"

  get "wms_parameters/update_constrained_options"

  get "wms_parameters/edit_constrained_options_popup"

  get "wms_parameters/remove_constrained_options"

  get "wms_parameters/new_popup"

  get "wms_parameters/add_new_parameters"

  get "wms_parameters/localise_globalise_parameter"

  get "wms_parameters/make_optional_or_mandatory"

  get "wms_parameters/destroy"

  get "wms_parameters/authorise"

  get "wms_parameters/get_redirect_url"

  get "wms_parameters/destroy_method_param_map"

  get "wms_parameters/find_rest_parameter"

  get "wms_parameters/find_rest_method"

  get "wms_parameters/find_rest_methods"

  get "wms_representations/show"

  get "wms_representations/annotations"

  get "wms_representations/new_popup"

  get "wms_representations/add_new_representations"

  get "wms_representations/destroy"

  get "wms_representations/authorise"

  get "wms_representations/find_rest_method"

  get "wms_representations/find_rest_methods"

  get "wms_representations/find_rest_representation"

  get "wms_representations/get_redirect_url"

  get "wms_representations/destroy_method_rep_map"

  get "wms_resources/new_popup"

  get "wms_resources/add_new_resources"

  get "wms_resources/index"

  get "wms_resources/show"

  get "wms_resources/annotations"

  get "wms_resources/methods"

  get "wms_resources/parse_sort_params"

  get "wms_resources/authorise"

  get "wms_resources/find_wms_service"

  get "wms_resources/find_wms_resource"
=begin

  get "wms_services/new"

  get "wms_services/edit"

=end
 # get "wms_services/test"

  resources :oauth_clients

  match '/oauth/test_request' => 'oauth#test_request', :as => :test_request
  match '/oauth/access_token' => 'oauth#access_token', :as => :access_token
  match '/oauth/request_token' => 'oauth#request_token', :as => :request_token
  match '/oauth/authorize' => 'oauth#authorize', :as => :authorize
  match '/oauth' => 'oauth#index', :as => :oauth
  match '/curation' => 'curation#show', :as => :curation, :via => :get
  match '/curation/reports/potential_duplicate_operations_within_service' => 'curation#potential_duplicate_operations_within_service', :as => :curation_reports_potential_duplicate_operations_within_service, :via => :get
  match '/curation/reports/providers_without_services' => 'curation#providers_without_services', :as => :curation_reports_providers_without_services, :via => :get
  match '/curation/reports/services_missing_annotations' => 'curation#services_missing_annotations', :as => :curation_reports_services_missing_annotations, :via => [:get, :post]
  match '/curation/tools/copy_annotations' => 'curation#copy_annotations', :as => :curation_tools_copy_annotations, :via => [:get, :post]
  match '/curation/tools/copy_annotations_preview' => 'curation#copy_annotations_preview', :as => :curation_tools_copy_annotations_preview, :via => :post
  match '/curation/reports/annotation_level' => 'curation#annotation_level', :as => :curation_annotation_level, :via => :get
  match '/curation/reports/links_checker' => 'curation#links_checker', :as => :link_checker, :via => :get
  match '/curation/tools/download_latest_csv' => 'curation#download_latest_csv', :as => :download_latest_csv, :via => :get
  match '/curation/tools/csv_export' => 'curation#download_csv_page', :as => :download_csv_page, :via => :get
  match '/curation/elixir_curation' => 'curation#elixir_curation', :as => :elixir_curation, :via => :get

  match '/api.:format' => 'api#show', :as => :api
  match '/lookup.:format' => 'lookup#show', :as => :lookup
  match '/lookup' => 'lookup#show', :as => :lookup
=begin

  match '/wms_services/test' => 'wms_services#test'
=end

  resources :announcements

  resources :service_tests do

    member do
      get :results
      put :enable
      put :disable
      post :new_url_monitor_popup
      post :create_monitoring_endpoint
      post :edit_monitoring_endpoint_by_popup
      post :update_monitoring_endpoint
    end

  end

  resources :test_results

  resources :test_scripts do

    member do
      get :download
    end

  end

  match '/fail/:http_code' => 'fail#index', :as => :fail_page
  match '/stats' => 'stats#index', :as => :stats_index
  match '/stats/refresh' => 'stats#refresh', :as => :refresh_stats, :via => :post

  resources :stats do

    collection do
      get :general
      get :metadata
      get :tags
      get :search
    end
  end

  resources :categories do

    member do
      get :services
    end

  end

  resources :registries do

    member do
      get :annotations_by
      get :services
    end

  end

  resources :agents do

    member do
      get :annotations_by
    end

  end

  resources :annotations do

    collection do
      post :create_multiple
      post :new_popup
      post :create_inline
      post :filtered_index
      get :filters
      post :bulk_create
    end

    member do
      post :edit_popup
      post :promote_alternative_name
      get :download
    end

  end

  resources :annotation_attributes do

    member do
      get :annotations
    end

  end

  resources :tags, :only => [:index, :show, :destroy] do

    collection do
      delete :destroy_taggings
      post :auto_complete
    end


  end

  match '/search/auto_complete' => 'search#auto_complete', :as => :search_auto_complete, :via => :post
  match '/search/ignore_last' => 'search#ignore_last', :as => :ignore_last_search, :via => :post
  match '/search.:format' => 'search#show', :as => :search, :via => [:get, :post]
  match '/search' => 'search#show', :as => :search, :via => [:get, :post]
  match '/search/by_data.:format' => 'search#by_data', :as => :search_by_data, :via => [:get, :post]
  match '/search/by_data' => 'search#by_data', :as => :search_by_data, :via => [:post, :get]



  resources :service_providers do

    collection do
      post :filtered_index
      get :filters
      post :edit_by_popup
      post :auto_complete
    end

    member do
      get :annotations_by
      get :annotations
      get :services
      post :edit_by_popup
      put :upload_logo
      delete :remove_logo

      #for loading tab partials
      get :hostnames
      get :profile
      get :services
    end

  end

  resources :service_provider_hostnames do
    collection do
      post :reassign_provider_by_popup
      post :reassign_provider
    end
  end

  resources :service_deployments do

    member do
      get :annotations
      post :edit_location_by_popup
      post :update_location
    end

  end

  resources :users do

    collection do
      get :whoami
      get :activate_account
      post :filtered_index
      get :rpx_merge_setup
      get :filters
      post :rpx_merge
    end

    member do
      put :remove_curator
      get :annotations_by
      put :deactivate
      get :change_password
      post :change_password
      get :favourites
      get :rpx_update
      post :rpx_update
      put :activate
      get :services_responsible
      get :services_annotated
      get :services_submitted
      get :service_status_notifications
      get :service_status
      get :saved_searches
      get :services
      put :make_curator
    end

  end

  match '/termsofuse' => 'termsofuse#index'

  match '/session' => 'sessions#create', :as => :session, :via => :post

  if ENABLE_RPX
    match '/session/rpx_token' => 'sessions#rpx_token', :as => :session_rpx_token
  end

  match '/register' => 'users#new', :as => :register
  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/signin' => 'sessions#new', :as => :signin
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/activate_account/:security_token' => 'users#activate_account', :as => :activate_account, :security_token => nil
  match '/forgot_password' => 'users#forgot_password', :as => :forgot_password
  match '/request_reset_password' => 'users#request_reset_password', :as => :request_reset_password
  match '/reset_password/:security_token' => 'users#reset_password', :as => :reset_password, :security_token => nil
  match '/contact' => 'contact#create', :as => :submit_feedback, :via => :post
  match '/contact' => 'contact#index', :as => :contact, :via => :get
  match '/' => 'home#index', :as => :home
  match '/index.:format' => 'home#index', :as => :activity_feed
  match '/status_changes.:format' => 'home#status_changes', :as => :status_changes_feed

  match '/latest' => 'latest#show', :as => :latest
  match 'service_providers/auto_complete' => 'service_providers#auto_complete', :as => :service_provider_auto_complete, :via => :post


  resources :latest do
    collection do
      get :activity

app/helpers/service_tests_helper.rb
# BioCatalogue: app/helpers/service_test_helper.rb
#
# Copyright (c) 2009-2010, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details.

module ServiceTestsHelper
  
  def sort_li_class_helper(param, order)
    result = 'class="sortup"' if (params[:sort_by] == param && params[:sort_order] == order)
    result = 'class="sortdown"' if (params[:sort_by] == param && params[:sort_order] == reverse_order(order))  
    return result
  end
  
  def service_tests_sort_link_helper(text, param, order)
    key   = param
    order = order
    order = reverse_order(params[:sort_order]) if params[:sort_by] == param
    params.delete(:page) # reset page
    options = {
      :url => {:action => 'index', :params => params.merge({:sort_by => key , :sort_order => order})}, #:page =>param[:page]
      :update => {:success => 'service_tests'},
      :before => "Element.show('spinner')",
      :success => "Element.hide('spinner')"
      }
    html_options = {
      :title => "Sort by this field",
      :href => url_for(:action => 'index', :params => params.merge({:sort_by => key, :sort_order => order })) #:page => params[:page]
      }
    link_to_with_callbacks(text, options, html_options.merge(:remote => true))
  end
  
  def reverse_order(order)
    orders ={'asc' => 'desc', 'desc' => 'asc'}
    return orders[order]
  end
  
  # This method will create a link to a popup dialog, which allows the user to
  # add an 'endpoint' for (availability) monitoring.
  #
  # CONFIGURATION OPTIONS (all these options are optional)
  #  :tooltip_text - text that will be displayed in a tooltip over the text.
  #    default: 'Add a new endpoint for monitoring'
  #  :link_text - text to be displayed as part of the link.
  #    default: 'Add Monitoring Endpoint'
  #  :style - any CSS inline styles that need to be applied to the text.
  #    default: ''
  #  :class - any CSS class that need to be applied to the text.
  #    default: nil
  def add_monitoring_endpoint_by_popup_link(parent_service_instance, *args)
    return '' unless parent_service_instance.class == RestService
    
    return '' unless BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, parent_service_instance)
    
    return '' unless parent_service_instance.service.has_capacity_for_new_monitoring_endpoint?
    
    options = args.extract_options!
    
    # default config options
    options.reverse_merge!(:style => "",
                           :class => nil,
                           :link_text => "Add Monitoring Endpoint",
                           :tooltip_text => "Add a new endpoint for monitoring")

    default_styles = ""
    default_styles += "float: right; " unless options[:style].include?('float')
    default_styles += "font-weight: bold; " unless options[:style].include?('font-weight')
    
    options[:style] = default_styles + options[:style]

    link_content = ''
    
    inner_html = image_tag("add.png")
    inner_html += content_tag(:span, " " + options[:link_text])
    
    url_hash = { :controller => "service_tests", :action => "new_url_monitor_popup", :service_id => parent_service_instance.service.id }
    
    fail_value = "alert('Sorry, an error has occurred.'); RedBox.close();"
    id_value = "new_monitoring_endpoint_for_#{parent_service_instance.class.name}_#{parent_service_instance.id}_redbox"
  
    redbox_hash = { :url => url_hash, :id => id_value, :failure => fail_value }
    
    link_content = link_to_remote_redbox(inner_html, redbox_hash, create_redbox_css_hash(options))
    
    return link_content
  end
  
  # This method is used to generate an icon and/or link that will popup up an in page dialog box
  # for the user to edit an 'endpoint' for (availability) monitoring.
  #
  # It takes in the service test object that needs to be edited and some options (all optional):
  #  :tooltip_text - text that will be displayed in a tooltip over the icon/text.
  #    default: 'Edit'
  #  :style - any CSS inline styles that need to be applied to the icon/text.
  #    default: 'Update the URL used for monitoring by this service test'
  #  :class - the CSS class to apply to the link.
  #    default: '' 
  #  :link_text - text to be displayed as part of the link.
  #    default: 'edit'
  def monitoring_endpoint_edit_by_popup_link(service_test, *args)
    return '' unless service_test.class == ServiceTest
    return '' unless service_test.is_custom_endpoint_monitor? 
    
    return '' unless BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, service_test.service)
    
    options = args.extract_options!
    
    # default config options
    options.reverse_merge!(:style => "",
                           :class => nil,
                           :link_text => "Edit",
                           :tooltip_text => "Update the URL used for monitoring by this service test")

    options[:style] += "float: right; " unless options[:style].include?('float')
    options[:style] += "font-weight: bold; " unless options[:style].include?('font-weight')

    link_content = ''
    
    inner_html = image_tag("pencil.gif") + content_tag(:span, " " + options[:link_text])
    
    url_hash = { :controller => "service_tests", :action => "edit_monitoring_endpoint_by_popup", :id => service_test.id }

    fail_value = "alert('Sorry, an error has occurred.'); RedBox.close();"
    id_value = "edit_for_#{service_test.class.name}_#{service_test.id}_redbox"
    
    redbox_hash = {:url => url_hash, :id => id_value, :failure => fail_value}
    link_content = link_to_remote_redbox(inner_html, redbox_hash, create_redbox_css_hash(options).merge(:remote => true))
    
    return link_content
  end

end

app/views/service_tests/_gauge_graph.html.erb
<%
  
  # BioCatalogue: app/views/service_tests/_gauge_graph.html.erb
  #
  # Copyright (c) 2010, University of Manchester, The European Bioinformatics 
  # Institute (EMBL-EBI) and the University of Southampton.
  # See license.txt for details
  
%>

<!-- Gauge chart of percentage success of service test -->
<%= Seer::visualize(
           			[service_test], 
           			:as => :gauge,
           			:in_element => "chart",
           			:series => {:series_label => 'graph_label', :data_method => 'success_rate'},
           			:chart_options => {
             		:red_from => 0,
             		:red_to => 25,
             		:yellow_from => 26,
             		:yellow_to => 75,
             		:green_from => 76,
             		:green_to => 100,
             		:width => 200,
             		:height => 100,
             		:max => 100,
             		:min => 0,
             		:minor_ticks => 5
           				}
         			)
      			-%>

app/views/service_tests/_line_chart.html.erb
<%
  
  # BioCatalogue: app/views/service_tests/_line_chart.html.erb
  #
  # Copyright (c) 2010, University of Manchester, The European Bioinformatics 
  # Institute (EMBL-EBI) and the University of Southampton.
  # See license.txt for details
  
%>

<%unless service_test.unchecked? %>
	<%= Seer::visualize(
      	[service_test], 
      	:as => :line_chart,
      	:in_element => 'line_chart',
      	:series => {
        	:series_label => 'name',
        	:data_label => 'date',
        	:data_method => 'result',
        	:data_series => service_test.result_values
      	},
      	:chart_options => { 
        	:height => 300,
        	:width => 950,
        	:axis_font_size => 10,
        	:colors => ['#0000ff','#0000ff','#0000ff'],
        	:title => "Number of Failures over Period",
        	:point_size => 3
      	}
     	).html_safe
 	-%>
 <%end%>

app/views/service_tests/_listing.html.erb
<%

# BioCatalogue: app/views/service_tests/_listing.html.erb
#
# Copyright (c) 2010, University of Manchester, The European Bioinformatics 
# Institute (EMBL-EBI) and the University of Southampton.
# See license.txt for details

%>

<div class="listings">
	<% items.each do |st| %>
			
		<% if st.enabled? %>
		
			<div class="listing_item" >
				<div class="name">
					<%= link_to(display_name(st), service_test_path(st)) -%> 
				</div>
				<div>
					<%= service_test_status_symbol(st)%>
					
					<% unless st.unchecked? || !st.success_rate-%>
						<div id="chart_info" style="float:right;" >
							<span style="font-size: 3em;"><%= st.success_rate -%>%</span>
							<%= info_icon_with_tooltip("Historical success rate for this test since its monitoring started.") -%>
						</div>
					<%end%>
				</div>
				
			
				<div class="detail" style="text-align: left;">
				   <table width="50%">
				   	  <tr>
				   	  	<td width="25%">
				   	  	<b>Monitored Since :</b>
						<% if ms = st.monitored_since %> 
							  <%=h ms -%>
						<%else%>
							<b>Not yet!<b/>
						<%end%>
						</td>
						<td width="25%"><%= info_icon_with_tooltip("parent service for this test") -%><%= link_to(display_name(st.service), service_path(st.service)) -%></td>
					  </tr>
				  </table>
				</div>
			</div>
			
		<% else %>
		
			<div class="listing_item archived" >
				<div class="name">
					<%= link_to(display_name(st), service_test_path(st)) -%> 
				</div>
				
				<p class="archived_status_text">
					This service test has been disabled.
	            </p>	
			</div>
			
		<% end %>
	<%end%>	
	
</div>

app/views/service_tests/_test_script_show.html.erb
<%
  
  # BioCatalogue: app/views/service_tests/_testscript_show.html.erb
  #
  # Copyright (c) 2010, University of Manchester, The European Bioinformatics 
  # Institute (EMBL-EBI) and the University of Southampton.
  # See license.txt for details
  
%>

<div class="box_info_standout" style="text-align:center;">
	<!--About <b>Test scripts:</b>-->
	<%= link_to_function(("Click here for more info on test scripts" + expand_image).html_safe, visual_effect(:toggle_blind, "about_testscripts", :duration => 0.3), :style => "text-decoration:none;").html_safe %>
	<div id="about_testscripts" style="display:none;">
		<%= render :partial => "test_scripts/about_testscripts" -%>
	</div>
</div>


<div id="tab-testscripts" class="tabbertab">
	<div class="monitoring_section">
		
		<div style="text-align: right;">
			<%= link_to("Download", download_test_script_url(service_test.test), :class => "button_slim") -%>
			<%if logged_in? && BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, service_test.service) %>
					<% if service_test.activated? %>
						<%= link_to("Disable", disable_service_test_url(service_test), :method => :put, :confirm => "Are you sure you want to disable this test?", :class => "button_slim") -%>
					<% else %>
						<%= link_to("Enable", enable_service_test_url(service_test), :method => :put, :confirm => "Are you sure you want to enable this test?", :class => "button_slim") -%>
					<% end %>
					<%= link_to("Remove", service_test_url(service_test), :method => :delete, :confirm => "Are you sure you want to remove this test? All its history will be removed as well.", :class => "button_slim") -%>
			<%end%>
		</div>
		
		<% if !service_test.activated? -%>
			<div id="disable_test" style="text-align:center; color:red" >
				<span style="font-size: 3em;">DISABLED </span>
					<%= info_icon_with_tooltip("This service test has been disabled. It is status does not affect the current service status.") -%>
			</div>
		<% end -%>
		
		<ul>
			<!--<h4>Test Scripts for this Service</h4>-->
			<div class="monitoring_section">		
				<h5><%= h service_test.test.name -%> </h5>
				<% unless service_test.unchecked? -%>
					<div id="chart_info" style="float:right;" >
						<span style="font-size: 3em;"><%= service_test.success_rate -%> % </span>
						<%= info_icon_with_tooltip("Historical success rate for this test since its monitoring started.") -%>
					</div>
				<%end%>	
				
				<div style="text-align: left;">
					<p>
						<% if ms = service_test.monitored_since %> 
							<b>Monitored Since : </b>  <%=h ms -%>
						<%end%>
					</p>
				</div>
				
				<div style="padding-right: 1em;">
					<%= service_test_status_symbol(service_test)%>
				</div>	
				
				<div class="property">
					<b>Submitter / Source:</b>
					<%= submitter_link(service_test.test.submitter) %>
					<span class="ago" style="vertical-align: baseline;">
						(<%= distance_of_time_in_words_to_now(service_test.test.created_at) -%> ago)
					</span>
				</div>
									
				<div class="property">
					<%= render :partial => "annotations/descriptions",
    				 		   :locals => { :annotatable => service_test.test } -%>
				</div>
										
				<!--history -->
				<% if MONITORING_HISTORY_LIMIT > 0 %>
					<p>
						<b>Recent History</b>
					</p>
					<div class="box_indented_with_bar">
						<ul>
							<% unless (script_hist = service_test.test.recent_test_results(MONITORING_HISTORY_LIMIT)).blank? %>
								<% script_hist.each  do |hist| %>
									<% unless hist.result == -1  %>
										<li>
											<%= test_result_status_symbol(hist)  %> 
											<%= distance_of_time_in_words_to_now(hist.created_at) -%> ago
										</li>
									<% end %>
								<% end %>
							<% else %>
								<li class="none_text">No previous checks</li>
							<% end %>
						</ul>
					</div>
				<% end %>

				<% if SHOW_MONITORING_GRAPH %>
					<%unless service_test.latest_status.label.downcase == 'unchecked' %>
						<div id="line_chart" style="margin-top: 2em; border-top: 2px solid #CCF; padding-top: 1em;" ></div>
					<%end%>
				<% end %>
				
			</div>	
		</ul>	

	</div>
</div>

<div>
	<% if BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, service_test.service) -%>
		<div id='tests' style="margin-top: 2em; border-top: 2px solid #CCF; padding-top: 1em;">
			<%= render :partial => 'shared/service_test', :locals => {:service => service_test.service} -%>
		</div>
	<% end %>
</div>

<%=render :partial => 'line_chart', :locals => {:service_test => service_test } -%>

app/views/service_tests/_url_monitor_show.html.erb
<%
  
  # BioCatalogue: app/views/service_tests/_urlmonitor_show.html.erb
  #
  # Copyright (c) 2010, University of Manchester, The European Bioinformatics 
  # Institute (EMBL-EBI) and the University of Southampton.
  # See license.txt for details
  
%>

<div id="tab-availability" class="tabbertab">
	<div>
		<% if service_test.activated? || logged_in? || (logged_in? && BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, service_test.service)) -%>		
			<div class="monitoring_section">
				
				<div style="text-align: right;">
					<%if logged_in? && BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, service_test.service) %>						
						<% if ( service_test.activated? ) %>
							<%= link_to("Disable", disable_service_test_url(service_test), :method => :put, :confirm => "Are you sure you want to disable this test?", :class => "button_slim", :style => "float:right;") -%>
						<% else %>
							<%= link_to("Enable", enable_service_test_url(service_test), :method => :put, :confirm => "Are you sure you want to enable this test?", :class => "button_slim", :style => "float:right;") -%>
						<% end %>

						<%= monitoring_endpoint_edit_by_popup_link(service_test, :link_text => "Update", :class => "button_slim", :style => "margin-right:1em;") -%>
					<% end -%>
				</div>	
				
				<% if !service_test.activated? -%>
					<div id="disable_test" style="text-align:center; color:red" >
					 	<span style="font-size: 3em;">DISABLED </span>
					 	<%= info_icon_with_tooltip("This service test has been disabled. It is status does not affect the current service status.") -%>
					</div>
				<% end -%>
				
				<h5>
					<div style="text-align: left;"> 
						<p>
							<% if service_test.test.parent_type =="Annotation" -%>
								<%= h(service_test.test.parent.attribute.name.titleize) -%> :
								<% annotation_value = service_test.test.parent.send(service_test.test.property) %>
								<% pingable_item = BioCatalogue::Monitoring.pingable_url(annotation_value) %>
								<% if pingable_item.nil? %>
									<span class="none_text">No valid URL for monitoring could be found</span>
								<% else %>
									<% if service_test.is_custom_endpoint_monitor? %>
										<% if BioCatalogue::Auth.allow_user_to_curate_thing?(current_user, service_test.service) %>
											<%=h pingable_item -%>
										<% else %>
											<span class="none_text">Not available for public viewing</span>
										<% end %>
									<% else %>
										<%=h pingable_item -%>
									<% end %>
								<% end %> 
							<%else%>
								<%= h(service_test.test.property.titleize) -%> :
								<%= h(service_test.test.parent.send(service_test.test.property)) -%> 
							<%end%>
						</p>
					</div>	
				</h5>
				<% unless service_test.unchecked? -%>
					<div id="chart_info" style="float:right;" >
					 	<span style="font-size: 3em;"><%= service_test.success_rate -%> % </span>
					 	<%= info_icon_with_tooltip("Historical success rate for this test since its monitoring started.") -%>
					</div>
				<%end%>
				
				<div style="text-align: left;">
					<p>
						<% if ms = service_test.monitored_since -%> 
							<b></>Monitored Since :</b>  <%=h ms -%>
						<%end%>
					</p>
				</div>
							
				<div style="padding-right: 1em;">
					<%= service_test_status_symbol(service_test) -%>
				</div>
	
				<% if MONITORING_HISTORY_LIMIT > 0 %>
					<p>
						<b>Recent History</b>
					</p>
					<div class="box_indented_with_bar">
						<ul>
							<% unless (test_hist = service_test.recent_test_results(MONITORING_HISTORY_LIMIT)).blank? -%>
								<% test_hist.each do |hist| %>
								<li class="container_middled">
									<%= test_result_status_symbol(hist) %> 
									<span><%= distance_of_time_in_words_to_now(hist.created_at) -%> ago</span>
								</li>
							<% end %>
							<% else %>
								<li class="none_text">No previous checks</li>
							<% end %>
						</ul>
					</div>
				<% end %>
						
				<% if SHOW_MONITORING_GRAPH %>			
					<%unless service_test.latest_status.label.downcase == 'unchecked' %>
						<div id="line_chart" style="margin-top: 2em; border-top: 2px solid #CCF; padding-top: 1em;" ></div>
					<%end%>
				<% end %>
				
			</div>
		<%end%>
	</div>
</div>

<%=render :partial => 'line_chart', :locals => {:service_test => service_test } -%>